# Generated by Django 2.0.13 on 2019-02-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
